version: "3"

services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/app:ro
    network_mode: host

  postgres:
    image: postgres
    env_file:
      - docker.env

    volumes:
      - POSTGRES_DB:/var/lib/postgresql/data

volumes:
  POSTGRES_DB: